
Currently Loaded Modules:
  1) tensorflow/2.6.0

 

2025-07-09 18:13:33.263651: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1938] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 10.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-07-09 18:14:30.162291: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1938] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 10.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-07-09 18:14:30.162697: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-09 18:14:30.167787: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1938] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 10.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-07-09 18:14:43.896272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 180450 MB memory:  -> device: 0, name: NVIDIA B200, pci bus id: 0000:43:00.0, compute capability: 10.0
2025-07-09 18:14:46.251530: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2025-07-09 18:17:18.329249: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2025-07-09 18:17:18.353643: W tensorflow/core/framework/op_kernel.cc:1680] Invalid argument: required broadcastable shapes
2025-07-09 18:17:18.354564: W tensorflow/core/framework/op_kernel.cc:1680] Invalid argument: required broadcastable shapes
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "train_gnn.py", line 354, in <module>
    main()
  File "train_gnn.py", line 346, in main
    model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=20)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  required broadcastable shapes
	 [[node mean_squared_error/SquaredDifference (defined at train_gnn.py:346) ]] [Op:__inference_train_function_1049]

Function call stack:
train_function

2025-07-09 18:17:18.474420: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
